### ISSUE TITLE
divspl fails on ranges above 6664 on windows

### ISSUE THREAD

**Issue by bowbahdoe** [di/divspl#5]
when running the following divspl program, printing of values abruptly stops halfway through 6665.
`1...7000
even = 2
`
With the output ending with
`even
6657
even
6659
even
6661
even
6663
even
66  `

This test was performed using cmd.exe on Windows, and might be platform dependent

**Comment by di** [comment]
Hi @bowbahdoe! That's a curious problem. I've never tried to use `divspl` on Windows, so it's possible there may be issues.

I'm curious though if it's an issue that the output is just getting clipped for some reason? If you change your `divspl` program to print less characters, does it make it to 7000? For example:

```
1...7000
e=2
```

**Comment by bowbahdoe** [comment]
Yeah, that program works fine. If I increase the character count the output gets chopped off more, and when I increase the range to something like 10000000 the program waits for awhile then prints the output all at once.

It might just be an artifact of printing the entire string at once. In MainBox.eval you return a long string that is the entirety of the output. Its possible that on Windows there is a limit to how much you can output on a single write.

Maybe if eval returned the list of strings instead of one long string, then changing
 
    os.write(1, _bytes(result.eval()))`

to

    for number in result.eval():
         os.write(1, _bytes(number))`

would solve the problem. 

I am going to test that now.

**Comment by bowbahdoe** [comment]
That seems to work to solve the problem, though it prints slower with CPython. I don't know how that will affect the speed of the interpreter when compiled with RPython.
